name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests and generate coverage
        run: |
          npm run test:coverage || echo "Coverage threshold not met, but continuing deployment"
      
      - name: Build
        run: |
          NODE_ENV=production npm run build
      
      - name: Copy coverage report to dist
        run: |
          if [ -d "coverage" ]; then
            cp -r coverage dist/coverage
          fi
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist